enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

#inotia00
#[YouTube]
#apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
#patches-source = "inotia00/revanced-patches"
#integrations-source = "inotia00/revanced-integrations"
#patches-version = "v4.9.2-dev.1"
#integrations-version = "v1.10.2-dev.1"
#cli-source = "inotia00/revanced-cli"
#rv-brand = "inotia00 ReVanced"
#build-mode = "module"
#version = "19.16.39"
#included-patches = "'Custom header for YouTube' 'Force hide player buttons background' 'Hide Shorts dimming' 'Hide animated button background' 'Hide double tap overlay filter' 'Hide double tap to like animations' 'MaterialYou' 'Visual preferences icons'"
#excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Custom package name' 'Theme'"

#[Music]
#apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
#patches-source = "inotia00/revanced-patches"
#integrations-source = "inotia00/revanced-integrations"
#patches-version = "v4.9.2-dev.1"
#integrations-version = "v1.10.2-dev.1"
#cli-source = "inotia00/revanced-cli"
#rv-brand = "inotia00 ReVanced"
#arch = "arm64-v8a"
#build-mode = "module"
#version = "7.05.53"
#included-patches = "'Hide double tap overlay filter' 'Hide overlay filter' 'Hide player overlay filter'"
#excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Custom package name'"

#anddea
[YouTube]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
patches-version = "v2.226.0-dev.16"
integrations-version = "v0.153.0-dev.8"
cli-source = "inotia00/revanced-cli"
rv-brand = "anddea ReVanced"
build-mode = "module"
version = "19.21.40"
included-patches = "'Force custom branding wordmark header' 'Force hide player buttons background' 'Hide Shorts dimming' 'Hide animated button background' 'Hide double tap to like animations' 'MaterialYou'"
excluded-patches = "'Custom package name' 'Theme'"

[Music]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
patches-version = "v2.226.0-dev.16"
integrations-version = "v0.153.0-dev.8"
cli-source = "inotia00/revanced-cli"
rv-brand = "anddea ReVanced"
arch = "arm64-v8a"
build-mode = "module"
version = "7.05.52"
included-patches = "'Hide overlay filter' 'Hide player overlay filter'"
excluded-patches = "'Custom package name'"

#[X]
#apkmirror-dlurl = "https://apkmirror.com/apk/x-corp/twitter/"
#patches-source = "crimera/piko"
#integrations-source = "crimera/revanced-integrations"
#patches-version = "v1.31.1"
#integrations-version = "v1.20.1"
#rv-brand = "crimera ReVanced"
#build-mode = "module"
#included-patches = "'Hide FAB' 'Customize Navigation Bar items' 'Delete from database' 'Force enable translate' 'Hide promote button' 'Hide Community Notes' 'Hide Banner' 'Hide Live Threads' 'Add ability to copy media link' 'Disable chirp font'"
