enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

#[YouTube]
#apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
#uptodown-dlurl = "https://youtube.en.uptodown.com/android"
#patches-source = "inotia00/revanced-patches"
#integrations-source = "inotia00/revanced-integrations"
#cli-source = "inotia00/revanced-cli"
#rv-brand = "inotia00 ReVanced"
#build-mode = "module"
#version = "19.16.39"
#patches-version = "v4.12.1"
#integrations-version = "v1.12.1"
#included-patches = "'Custom header for YouTube' 'Force hide player buttons background' 'Hide Shorts dimming' 'MaterialYou' 'Visual preferences icons'"
#excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Theme'"

#[Music]
#apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
#uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
#patches-source = "inotia00/revanced-patches"
#integrations-source = "inotia00/revanced-integrations"
#cli-source = "inotia00/revanced-cli"
#rv-brand = "inotia00 ReVanced"
#arch = "arm64-v8a"
#build-mode = "module"
#version = "7.13.52"
#patches-version = "v4.12.1"
#integrations-version = "v1.12.1"
#included-patches = "'Hide overlay filter' 'Hide player overlay filter'"
#excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music'"

[X]
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
rv-brand = "piko ReVanced"
build-mode = "module"
version = "10.49.0-release.0"
patches-version = "v1.35.0-dev.1"
integrations-version = "v1.24.0-dev.2"
included-patches = "'Disable chirp font' 'Add ability to copy media link' 'Hide Banner' 'Hide Community Notes' 'Hide promote button' 'Force enable translate' 'Delete from database' 'Control video auto scroll' 'Remove premium upsell' 'Hide FAB' 'Customize Navigation Bar items'"
