enable-magisk-update = true
parallel-jobs = 2

patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
patches-version = "dev"

[YouTube]
build-mode = "module"
version = "19.47.53"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
included-patches = "'Disable resuming Shorts on startup' 'Force hide player buttons background' 'Fullscreen components' 'Hide action buttons' 'Hide ads' 'Hide comments components' 'Hide feed components' 'Hide layout components' 'Hide player buttons' 'MaterialYou' 'Miniplayer' 'Navigation bar components' 'Open links externally' 'Overlay buttons' 'Player components' 'Remove background playback restrictions' 'Remove viewer discretion dialog' 'Seekbar components' 'Settings for YouTube' 'Shorts components' 'Spoof streaming data' 'Swipe controls' 'Toolbar components' 'Translations for YouTube' 'Video playback' 'Visual preferences icons for YouTube'"
exclusive-patches = true
patcher-args = "-e 'Overlay buttons' -OchangeTopButtons=true -e 'Translations for YouTube' -OselectedTranslations=ja-rJP -OselectedStringResources=ja "

[Music]
build-mode = "module"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
included-patches = "'Dark theme' 'Hide action bar components' 'Hide ads' 'Hide layout components' 'Hide player overlay filter' 'Navigation bar components' 'Player components' 'Remove background playback restrictions' 'Remove viewer discretion dialog' 'Settings for YouTube Music' 'SponsorBlock' 'Spoof player parameter' 'Translations for YouTube Music' 'Visual preferences icons for YouTube Music'"
exclusive-patches = true
patcher-args = "-e 'Dark theme' -OmaterialYou=true -e 'Translations for YouTube Music' -OselectedTranslations=ja-rJP -OselectedStringResources=ja "
