enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
patches-version = "v4.10.1-dev.2"
integrations-version = "v1.11.1-dev.2"
cli-source = "inotia00/revanced-cli"
rv-brand = "inotia00 ReVanced"
build-mode = "module"
version = "19.16.39"
included-patches = "'Custom header for YouTube' 'Force hide player buttons background' 'Hide Shorts dimming' 'MaterialYou' 'Visual preferences icons'"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Custom package name' 'Theme'"

[Music]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
patches-version = "v4.10.1-dev.2"
integrations-version = "v1.11.1-dev.2"
cli-source = "inotia00/revanced-cli"
rv-brand = "inotia00 ReVanced"
arch = "arm64-v8a"
build-mode = "module"
version = "7.07.51"
included-patches = "'Hide overlay filter' 'Hide player overlay filter'"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Custom package name' 'Enable Cairo splash animation'"

#[X]
#apkmirror-dlurl = "https://apkmirror.com/apk/x-corp/twitter/"
#patches-source = "crimera/piko"
#integrations-source = "crimera/revanced-integrations"
#patches-version = "v1.31.2"
#integrations-version = "v1.20.1"
#rv-brand = "crimera ReVanced"
#build-mode = "module"
#included-patches = "'Hide FAB' 'Customize Navigation Bar items' 'Delete from database' 'Force enable translate' 'Hide promote button' 'Hide Community Notes' 'Hide Banner' 'Hide Live Threads' 'Add ability to copy media link' 'Disable chirp font'"
